// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: pkg/program.proto

package serde

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenKind int32

const (
	TokenKind_PROGRAM    TokenKind = 0
	TokenKind_ASSIGN     TokenKind = 1
	TokenKind_IDENTIFIER TokenKind = 2
	TokenKind_UINTLIT    TokenKind = 3
)

// Enum value maps for TokenKind.
var (
	TokenKind_name = map[int32]string{
		0: "PROGRAM",
		1: "ASSIGN",
		2: "IDENTIFIER",
		3: "UINTLIT",
	}
	TokenKind_value = map[string]int32{
		"PROGRAM":    0,
		"ASSIGN":     1,
		"IDENTIFIER": 2,
		"UINTLIT":    3,
	}
)

func (x TokenKind) Enum() *TokenKind {
	p := new(TokenKind)
	*p = x
	return p
}

func (x TokenKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_program_proto_enumTypes[0].Descriptor()
}

func (TokenKind) Type() protoreflect.EnumType {
	return &file_pkg_program_proto_enumTypes[0]
}

func (x TokenKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenKind.Descriptor instead.
func (TokenKind) EnumDescriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{0}
}

//////////////////////////////////
//  PROGRAM
//////////////////////////////////
type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=SerdeAst.TokenKind" json:"kind,omitempty"`
	Name   string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params []string  `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Block  *Block    `protobuf:"bytes,4,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Program) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stmts []*Statement `protobuf:"bytes,1,rep,name=stmts,proto3" json:"stmts,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetStmts() []*Statement {
	if x != nil {
		return x.Stmts
	}
	return nil
}

//////////////////////////////////
//  STATEMENTS
//////////////////////////////////
type AssignStmt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable string `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value    int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AssignStmt) Reset() {
	*x = AssignStmt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignStmt) ProtoMessage() {}

func (x *AssignStmt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignStmt.ProtoReflect.Descriptor instead.
func (*AssignStmt) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{2}
}

func (x *AssignStmt) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

func (x *AssignStmt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProcedureStmt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProcedureStmt) Reset() {
	*x = ProcedureStmt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureStmt) ProtoMessage() {}

func (x *ProcedureStmt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureStmt.ProtoReflect.Descriptor instead.
func (*ProcedureStmt) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{3}
}

func (x *ProcedureStmt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Statement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=SerdeAst.TokenKind" json:"kind,omitempty"`
	// Types that are assignable to Stmt:
	//	*Statement_AssignStmt
	//	*Statement_ProcStmt
	Stmt isStatement_Stmt `protobuf_oneof:"stmt"`
}

func (x *Statement) Reset() {
	*x = Statement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{4}
}

func (x *Statement) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (m *Statement) GetStmt() isStatement_Stmt {
	if m != nil {
		return m.Stmt
	}
	return nil
}

func (x *Statement) GetAssignStmt() *AssignStmt {
	if x, ok := x.GetStmt().(*Statement_AssignStmt); ok {
		return x.AssignStmt
	}
	return nil
}

func (x *Statement) GetProcStmt() *ProcedureStmt {
	if x, ok := x.GetStmt().(*Statement_ProcStmt); ok {
		return x.ProcStmt
	}
	return nil
}

type isStatement_Stmt interface {
	isStatement_Stmt()
}

type Statement_AssignStmt struct {
	AssignStmt *AssignStmt `protobuf:"bytes,2,opt,name=assignStmt,proto3,oneof"`
}

type Statement_ProcStmt struct {
	ProcStmt *ProcedureStmt `protobuf:"bytes,3,opt,name=procStmt,proto3,oneof"`
}

func (*Statement_AssignStmt) isStatement_Stmt() {}

func (*Statement_ProcStmt) isStatement_Stmt() {}

//////////////////////////////////
//  EXPRESSIONS
//////////////////////////////////
type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=SerdeAst.TokenKind" json:"kind,omitempty"`
	// Types that are assignable to Expr:
	//	*Expression_Id
	//	*Expression_Uint
	Expr isExpression_Expr `protobuf_oneof:"expr"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{5}
}

func (x *Expression) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (m *Expression) GetExpr() isExpression_Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (x *Expression) GetId() *Identifier {
	if x, ok := x.GetExpr().(*Expression_Id); ok {
		return x.Id
	}
	return nil
}

func (x *Expression) GetUint() *UIntLiteral {
	if x, ok := x.GetExpr().(*Expression_Uint); ok {
		return x.Uint
	}
	return nil
}

type isExpression_Expr interface {
	isExpression_Expr()
}

type Expression_Id struct {
	Id *Identifier `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Expression_Uint struct {
	Uint *UIntLiteral `protobuf:"bytes,3,opt,name=uint,proto3,oneof"`
}

func (*Expression_Id) isExpression_Expr() {}

func (*Expression_Uint) isExpression_Expr() {}

type Identifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{6}
}

func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UIntLiteral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UIntLiteral) Reset() {
	*x = UIntLiteral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_program_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIntLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIntLiteral) ProtoMessage() {}

func (x *UIntLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_program_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIntLiteral.ProtoReflect.Descriptor instead.
func (*UIntLiteral) Descriptor() ([]byte, []int) {
	return file_pkg_program_proto_rawDescGZIP(), []int{7}
}

func (x *UIntLiteral) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_pkg_program_proto protoreflect.FileDescriptor

var file_pkg_program_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x53, 0x65, 0x72, 0x64, 0x65, 0x41, 0x73, 0x74, 0x22, 0x85, 0x01,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x27, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x64, 0x65, 0x41,
	0x73, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x53, 0x65, 0x72, 0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x32, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x29,
	0x0a, 0x05, 0x73, 0x74, 0x6d, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x53, 0x65, 0x72, 0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x73, 0x74, 0x6d, 0x74, 0x73, 0x22, 0x3e, 0x0a, 0x0a, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xab,
	0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x72,
	0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53,
	0x74, 0x6d, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53, 0x65, 0x72, 0x64,
	0x65, 0x41, 0x73, 0x74, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x48,
	0x00, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x35, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x63, 0x53, 0x74, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x53, 0x65, 0x72, 0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x64, 0x75, 0x72, 0x65, 0x53, 0x74, 0x6d, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63,
	0x53, 0x74, 0x6d, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x74, 0x6d, 0x74, 0x22, 0x92, 0x01, 0x0a,
	0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x64,
	0x65, 0x41, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x53, 0x65, 0x72, 0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x04,
	0x75, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65, 0x72,
	0x64, 0x65, 0x41, 0x73, 0x74, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61,
	0x6c, 0x48, 0x00, 0x52, 0x04, 0x75, 0x69, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x65, 0x78, 0x70,
	0x72, 0x22, 0x20, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x55, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x41, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x53, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x49, 0x4e, 0x54, 0x4c, 0x49, 0x54, 0x10, 0x03, 0x42, 0x13, 0x5a, 0x11, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x64, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_program_proto_rawDescOnce sync.Once
	file_pkg_program_proto_rawDescData = file_pkg_program_proto_rawDesc
)

func file_pkg_program_proto_rawDescGZIP() []byte {
	file_pkg_program_proto_rawDescOnce.Do(func() {
		file_pkg_program_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_program_proto_rawDescData)
	})
	return file_pkg_program_proto_rawDescData
}

var file_pkg_program_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_program_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_program_proto_goTypes = []interface{}{
	(TokenKind)(0),        // 0: SerdeAst.TokenKind
	(*Program)(nil),       // 1: SerdeAst.Program
	(*Block)(nil),         // 2: SerdeAst.Block
	(*AssignStmt)(nil),    // 3: SerdeAst.AssignStmt
	(*ProcedureStmt)(nil), // 4: SerdeAst.ProcedureStmt
	(*Statement)(nil),     // 5: SerdeAst.Statement
	(*Expression)(nil),    // 6: SerdeAst.Expression
	(*Identifier)(nil),    // 7: SerdeAst.Identifier
	(*UIntLiteral)(nil),   // 8: SerdeAst.UIntLiteral
}
var file_pkg_program_proto_depIdxs = []int32{
	0, // 0: SerdeAst.Program.kind:type_name -> SerdeAst.TokenKind
	2, // 1: SerdeAst.Program.block:type_name -> SerdeAst.Block
	5, // 2: SerdeAst.Block.stmts:type_name -> SerdeAst.Statement
	0, // 3: SerdeAst.Statement.kind:type_name -> SerdeAst.TokenKind
	3, // 4: SerdeAst.Statement.assignStmt:type_name -> SerdeAst.AssignStmt
	4, // 5: SerdeAst.Statement.procStmt:type_name -> SerdeAst.ProcedureStmt
	0, // 6: SerdeAst.Expression.kind:type_name -> SerdeAst.TokenKind
	7, // 7: SerdeAst.Expression.id:type_name -> SerdeAst.Identifier
	8, // 8: SerdeAst.Expression.uint:type_name -> SerdeAst.UIntLiteral
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_program_proto_init() }
func file_pkg_program_proto_init() {
	if File_pkg_program_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_program_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignStmt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureStmt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_program_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIntLiteral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_program_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Statement_AssignStmt)(nil),
		(*Statement_ProcStmt)(nil),
	}
	file_pkg_program_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Expression_Id)(nil),
		(*Expression_Uint)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_program_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_program_proto_goTypes,
		DependencyIndexes: file_pkg_program_proto_depIdxs,
		EnumInfos:         file_pkg_program_proto_enumTypes,
		MessageInfos:      file_pkg_program_proto_msgTypes,
	}.Build()
	File_pkg_program_proto = out.File
	file_pkg_program_proto_rawDesc = nil
	file_pkg_program_proto_goTypes = nil
	file_pkg_program_proto_depIdxs = nil
}
