// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: program.proto

package serializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenKind int32

const (
	TokenKind_PROGRAM    TokenKind = 0
	TokenKind_ASSIGN     TokenKind = 1
	TokenKind_IDENTIFIER TokenKind = 2
	TokenKind_UINTLIT    TokenKind = 3
	TokenKind_PROCEDURE  TokenKind = 4
)

// Enum value maps for TokenKind.
var (
	TokenKind_name = map[int32]string{
		0: "PROGRAM",
		1: "ASSIGN",
		2: "IDENTIFIER",
		3: "UINTLIT",
		4: "PROCEDURE",
	}
	TokenKind_value = map[string]int32{
		"PROGRAM":    0,
		"ASSIGN":     1,
		"IDENTIFIER": 2,
		"UINTLIT":    3,
		"PROCEDURE":  4,
	}
)

func (x TokenKind) Enum() *TokenKind {
	p := new(TokenKind)
	*p = x
	return p
}

func (x TokenKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenKind) Descriptor() protoreflect.EnumDescriptor {
	return file_program_proto_enumTypes[0].Descriptor()
}

func (TokenKind) Type() protoreflect.EnumType {
	return &file_program_proto_enumTypes[0]
}

func (x TokenKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenKind.Descriptor instead.
func (TokenKind) EnumDescriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{0}
}

// ////////////////////////////////
//
//	TYPES
//
// ////////////////////////////////
type TypeKind int32

const (
	TypeKind_INTEGER TypeKind = 0
	TypeKind_REAL    TypeKind = 1
	TypeKind_BOOLEAN TypeKind = 2
	TypeKind_CHAR    TypeKind = 3
)

// Enum value maps for TypeKind.
var (
	TypeKind_name = map[int32]string{
		0: "INTEGER",
		1: "REAL",
		2: "BOOLEAN",
		3: "CHAR",
	}
	TypeKind_value = map[string]int32{
		"INTEGER": 0,
		"REAL":    1,
		"BOOLEAN": 2,
		"CHAR":    3,
	}
)

func (x TypeKind) Enum() *TypeKind {
	p := new(TypeKind)
	*p = x
	return p
}

func (x TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_program_proto_enumTypes[1].Descriptor()
}

func (TypeKind) Type() protoreflect.EnumType {
	return &file_program_proto_enumTypes[1]
}

func (x TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKind.Descriptor instead.
func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{1}
}

// ////////////////////////////////
//
//	PROGRAM
//
// ////////////////////////////////
type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.TokenKind" json:"kind,omitempty"`
	Name   string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params []string  `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Block  *Block    `protobuf:"bytes,4,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Program) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarDeclrs []*VarDeclaration `protobuf:"bytes,1,rep,name=varDeclrs,proto3" json:"varDeclrs,omitempty"`
	Stmts     []*Statement      `protobuf:"bytes,2,rep,name=stmts,proto3" json:"stmts,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetVarDeclrs() []*VarDeclaration {
	if x != nil {
		return x.VarDeclrs
	}
	return nil
}

func (x *Block) GetStmts() []*Statement {
	if x != nil {
		return x.Stmts
	}
	return nil
}

type VarDeclaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Expression `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type *Type       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *VarDeclaration) Reset() {
	*x = VarDeclaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarDeclaration) ProtoMessage() {}

func (x *VarDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarDeclaration.ProtoReflect.Descriptor instead.
func (*VarDeclaration) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{2}
}

func (x *VarDeclaration) GetName() *Expression {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *VarDeclaration) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

// ////////////////////////////////
//
//	STATEMENTS
//
// ////////////////////////////////
type AssignStmt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable *Expression `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value    *Expression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AssignStmt) Reset() {
	*x = AssignStmt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignStmt) ProtoMessage() {}

func (x *AssignStmt) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignStmt.ProtoReflect.Descriptor instead.
func (*AssignStmt) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{3}
}

func (x *AssignStmt) GetVariable() *Expression {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *AssignStmt) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProcedureStmt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Expression   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args []*Expression `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ProcedureStmt) Reset() {
	*x = ProcedureStmt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureStmt) ProtoMessage() {}

func (x *ProcedureStmt) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureStmt.ProtoReflect.Descriptor instead.
func (*ProcedureStmt) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{4}
}

func (x *ProcedureStmt) GetName() *Expression {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ProcedureStmt) GetArgs() []*Expression {
	if x != nil {
		return x.Args
	}
	return nil
}

type Statement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.TokenKind" json:"kind,omitempty"`
	// Types that are assignable to Stmt:
	//
	//	*Statement_AssignStmt
	//	*Statement_ProcStmt
	Stmt isStatement_Stmt `protobuf_oneof:"stmt"`
}

func (x *Statement) Reset() {
	*x = Statement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{5}
}

func (x *Statement) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (m *Statement) GetStmt() isStatement_Stmt {
	if m != nil {
		return m.Stmt
	}
	return nil
}

func (x *Statement) GetAssignStmt() *AssignStmt {
	if x, ok := x.GetStmt().(*Statement_AssignStmt); ok {
		return x.AssignStmt
	}
	return nil
}

func (x *Statement) GetProcStmt() *ProcedureStmt {
	if x, ok := x.GetStmt().(*Statement_ProcStmt); ok {
		return x.ProcStmt
	}
	return nil
}

type isStatement_Stmt interface {
	isStatement_Stmt()
}

type Statement_AssignStmt struct {
	AssignStmt *AssignStmt `protobuf:"bytes,2,opt,name=assignStmt,proto3,oneof"`
}

type Statement_ProcStmt struct {
	ProcStmt *ProcedureStmt `protobuf:"bytes,3,opt,name=procStmt,proto3,oneof"`
}

func (*Statement_AssignStmt) isStatement_Stmt() {}

func (*Statement_ProcStmt) isStatement_Stmt() {}

// ////////////////////////////////
//
//	EXPRESSIONS
//
// ////////////////////////////////
type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.TokenKind" json:"kind,omitempty"`
	// Types that are assignable to Expr:
	//
	//	*Expression_Id
	//	*Expression_Uint
	Expr isExpression_Expr `protobuf_oneof:"expr"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{6}
}

func (x *Expression) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (m *Expression) GetExpr() isExpression_Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (x *Expression) GetId() *Identifier {
	if x, ok := x.GetExpr().(*Expression_Id); ok {
		return x.Id
	}
	return nil
}

func (x *Expression) GetUint() *UIntLiteral {
	if x, ok := x.GetExpr().(*Expression_Uint); ok {
		return x.Uint
	}
	return nil
}

type isExpression_Expr interface {
	isExpression_Expr()
}

type Expression_Id struct {
	Id *Identifier `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Expression_Uint struct {
	Uint *UIntLiteral `protobuf:"bytes,3,opt,name=uint,proto3,oneof"`
}

func (*Expression_Id) isExpression_Expr() {}

func (*Expression_Uint) isExpression_Expr() {}

type Identifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{7}
}

func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UIntLiteral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UIntLiteral) Reset() {
	*x = UIntLiteral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIntLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIntLiteral) ProtoMessage() {}

func (x *UIntLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIntLiteral.ProtoReflect.Descriptor instead.
func (*UIntLiteral) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{8}
}

func (x *UIntLiteral) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tk TypeKind `protobuf:"varint,1,opt,name=tk,proto3,enum=Pasc.TypeKind" json:"tk,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Type_Int
	//	*Type_Real
	//	*Type_Bool
	//	*Type_Char
	Type isType_Type `protobuf_oneof:"type"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{9}
}

func (x *Type) GetTk() TypeKind {
	if x != nil {
		return x.Tk
	}
	return TypeKind_INTEGER
}

func (m *Type) GetType() isType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Type) GetInt() *Integer {
	if x, ok := x.GetType().(*Type_Int); ok {
		return x.Int
	}
	return nil
}

func (x *Type) GetReal() *Real {
	if x, ok := x.GetType().(*Type_Real); ok {
		return x.Real
	}
	return nil
}

func (x *Type) GetBool() *Boolean {
	if x, ok := x.GetType().(*Type_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *Type) GetChar() *Char {
	if x, ok := x.GetType().(*Type_Char); ok {
		return x.Char
	}
	return nil
}

type isType_Type interface {
	isType_Type()
}

type Type_Int struct {
	Int *Integer `protobuf:"bytes,2,opt,name=int,proto3,oneof"`
}

type Type_Real struct {
	Real *Real `protobuf:"bytes,3,opt,name=real,proto3,oneof"`
}

type Type_Bool struct {
	Bool *Boolean `protobuf:"bytes,4,opt,name=bool,proto3,oneof"`
}

type Type_Char struct {
	Char *Char `protobuf:"bytes,5,opt,name=char,proto3,oneof"`
}

func (*Type_Int) isType_Type() {}

func (*Type_Real) isType_Type() {}

func (*Type_Bool) isType_Type() {}

func (*Type_Char) isType_Type() {}

type Integer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Integer) Reset() {
	*x = Integer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integer) ProtoMessage() {}

func (x *Integer) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integer.ProtoReflect.Descriptor instead.
func (*Integer) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{10}
}

func (x *Integer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Boolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Boolean) Reset() {
	*x = Boolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boolean) ProtoMessage() {}

func (x *Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boolean.ProtoReflect.Descriptor instead.
func (*Boolean) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{11}
}

func (x *Boolean) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Real struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Real) Reset() {
	*x = Real{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Real) ProtoMessage() {}

func (x *Real) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Real.ProtoReflect.Descriptor instead.
func (*Real) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{12}
}

func (x *Real) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Char struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Char) Reset() {
	*x = Char{}
	if protoimpl.UnsafeEnabled {
		mi := &file_program_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Char) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Char) ProtoMessage() {}

func (x *Char) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Char.ProtoReflect.Descriptor instead.
func (*Char) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{13}
}

func (x *Char) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_program_proto protoreflect.FileDescriptor

var file_program_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x50, 0x61, 0x73, 0x63, 0x22, 0x7d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x62, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x32, 0x0a,
	0x09, 0x76, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x56, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x61,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x76, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x72,
	0x73, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x6d, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x73, 0x74, 0x6d, 0x74, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x56, 0x61, 0x72, 0x44,
	0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x62, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x2c,
	0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61,
	0x73, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x5b, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72,
	0x65, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x22, 0x9f, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x74,
	0x6d, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x6d, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63,
	0x53, 0x74, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x61, 0x73,
	0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x53, 0x74, 0x6d, 0x74, 0x48,
	0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x53, 0x74, 0x6d, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x73,
	0x74, 0x6d, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x75,
	0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x55, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x04,
	0x75, 0x69, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x22, 0x20, 0x0a, 0x0a,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23,
	0x0a, 0x0b, 0x55, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x02,
	0x74, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x02, 0x74, 0x6b, 0x12, 0x21, 0x0a, 0x03,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61,
	0x6c, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x48, 0x00,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x1d, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x1d, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a,
	0x0a, 0x04, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x43, 0x68,
	0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x50, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x53, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x49, 0x4e, 0x54, 0x4c, 0x49, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x4f,
	0x43, 0x45, 0x44, 0x55, 0x52, 0x45, 0x10, 0x04, 0x2a, 0x38, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42,
	0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x52,
	0x10, 0x03, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65,
	0x6e, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_program_proto_rawDescOnce sync.Once
	file_program_proto_rawDescData = file_program_proto_rawDesc
)

func file_program_proto_rawDescGZIP() []byte {
	file_program_proto_rawDescOnce.Do(func() {
		file_program_proto_rawDescData = protoimpl.X.CompressGZIP(file_program_proto_rawDescData)
	})
	return file_program_proto_rawDescData
}

var file_program_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_program_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_program_proto_goTypes = []interface{}{
	(TokenKind)(0),         // 0: Pasc.TokenKind
	(TypeKind)(0),          // 1: Pasc.TypeKind
	(*Program)(nil),        // 2: Pasc.Program
	(*Block)(nil),          // 3: Pasc.Block
	(*VarDeclaration)(nil), // 4: Pasc.VarDeclaration
	(*AssignStmt)(nil),     // 5: Pasc.AssignStmt
	(*ProcedureStmt)(nil),  // 6: Pasc.ProcedureStmt
	(*Statement)(nil),      // 7: Pasc.Statement
	(*Expression)(nil),     // 8: Pasc.Expression
	(*Identifier)(nil),     // 9: Pasc.Identifier
	(*UIntLiteral)(nil),    // 10: Pasc.UIntLiteral
	(*Type)(nil),           // 11: Pasc.Type
	(*Integer)(nil),        // 12: Pasc.Integer
	(*Boolean)(nil),        // 13: Pasc.Boolean
	(*Real)(nil),           // 14: Pasc.Real
	(*Char)(nil),           // 15: Pasc.Char
}
var file_program_proto_depIdxs = []int32{
	0,  // 0: Pasc.Program.kind:type_name -> Pasc.TokenKind
	3,  // 1: Pasc.Program.block:type_name -> Pasc.Block
	4,  // 2: Pasc.Block.varDeclrs:type_name -> Pasc.VarDeclaration
	7,  // 3: Pasc.Block.stmts:type_name -> Pasc.Statement
	8,  // 4: Pasc.VarDeclaration.name:type_name -> Pasc.Expression
	11, // 5: Pasc.VarDeclaration.type:type_name -> Pasc.Type
	8,  // 6: Pasc.AssignStmt.variable:type_name -> Pasc.Expression
	8,  // 7: Pasc.AssignStmt.value:type_name -> Pasc.Expression
	8,  // 8: Pasc.ProcedureStmt.name:type_name -> Pasc.Expression
	8,  // 9: Pasc.ProcedureStmt.args:type_name -> Pasc.Expression
	0,  // 10: Pasc.Statement.kind:type_name -> Pasc.TokenKind
	5,  // 11: Pasc.Statement.assignStmt:type_name -> Pasc.AssignStmt
	6,  // 12: Pasc.Statement.procStmt:type_name -> Pasc.ProcedureStmt
	0,  // 13: Pasc.Expression.kind:type_name -> Pasc.TokenKind
	9,  // 14: Pasc.Expression.id:type_name -> Pasc.Identifier
	10, // 15: Pasc.Expression.uint:type_name -> Pasc.UIntLiteral
	1,  // 16: Pasc.Type.tk:type_name -> Pasc.TypeKind
	12, // 17: Pasc.Type.int:type_name -> Pasc.Integer
	14, // 18: Pasc.Type.real:type_name -> Pasc.Real
	13, // 19: Pasc.Type.bool:type_name -> Pasc.Boolean
	15, // 20: Pasc.Type.char:type_name -> Pasc.Char
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_program_proto_init() }
func file_program_proto_init() {
	if File_program_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_program_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarDeclaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignStmt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureStmt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIntLiteral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Integer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Real); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_program_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Char); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_program_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Statement_AssignStmt)(nil),
		(*Statement_ProcStmt)(nil),
	}
	file_program_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Expression_Id)(nil),
		(*Expression_Uint)(nil),
	}
	file_program_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Type_Int)(nil),
		(*Type_Real)(nil),
		(*Type_Bool)(nil),
		(*Type_Char)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_program_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_program_proto_goTypes,
		DependencyIndexes: file_program_proto_depIdxs,
		EnumInfos:         file_program_proto_enumTypes,
		MessageInfos:      file_program_proto_msgTypes,
	}.Build()
	File_program_proto = out.File
	file_program_proto_rawDesc = nil
	file_program_proto_goTypes = nil
	file_program_proto_depIdxs = nil
}
