// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/program.proto

package serializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Callable_CallKind int32

const (
	Callable_Func Callable_CallKind = 0
	Callable_Proc Callable_CallKind = 1
)

// Enum value maps for Callable_CallKind.
var (
	Callable_CallKind_name = map[int32]string{
		0: "Func",
		1: "Proc",
	}
	Callable_CallKind_value = map[string]int32{
		"Func": 0,
		"Proc": 1,
	}
)

func (x Callable_CallKind) Enum() *Callable_CallKind {
	p := new(Callable_CallKind)
	*p = x
	return p
}

func (x Callable_CallKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Callable_CallKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_program_proto_enumTypes[0].Descriptor()
}

func (Callable_CallKind) Type() protoreflect.EnumType {
	return &file_proto_program_proto_enumTypes[0]
}

func (x Callable_CallKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Callable_CallKind.Descriptor instead.
func (Callable_CallKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{2, 0}
}

type FormalParameter_FPKind int32

const (
	FormalParameter_FuncHead   FormalParameter_FPKind = 0
	FormalParameter_ProcHead   FormalParameter_FPKind = 1
	FormalParameter_VarParam   FormalParameter_FPKind = 2
	FormalParameter_ValueParam FormalParameter_FPKind = 3
)

// Enum value maps for FormalParameter_FPKind.
var (
	FormalParameter_FPKind_name = map[int32]string{
		0: "FuncHead",
		1: "ProcHead",
		2: "VarParam",
		3: "ValueParam",
	}
	FormalParameter_FPKind_value = map[string]int32{
		"FuncHead":   0,
		"ProcHead":   1,
		"VarParam":   2,
		"ValueParam": 3,
	}
)

func (x FormalParameter_FPKind) Enum() *FormalParameter_FPKind {
	p := new(FormalParameter_FPKind)
	*p = x
	return p
}

func (x FormalParameter_FPKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormalParameter_FPKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_program_proto_enumTypes[1].Descriptor()
}

func (FormalParameter_FPKind) Type() protoreflect.EnumType {
	return &file_proto_program_proto_enumTypes[1]
}

func (x FormalParameter_FPKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormalParameter_FPKind.Descriptor instead.
func (FormalParameter_FPKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{3, 0}
}

// ////////////////////////////////
//
//	PROGRAM
//
// ////////////////////////////////
type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   TokenKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.TokenKind" json:"kind,omitempty"`
	Name   string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params []string  `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Block  *Block    `protobuf:"bytes,4,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetKind() TokenKind {
	if x != nil {
		return x.Kind
	}
	return TokenKind_PROGRAM
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Program) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarDecl   []*VarDeclaration `protobuf:"bytes,1,rep,name=varDecl,proto3" json:"varDecl,omitempty"`
	Stmts     []*Statement      `protobuf:"bytes,2,rep,name=stmts,proto3" json:"stmts,omitempty"`
	Callables []*Callable       `protobuf:"bytes,3,rep,name=callables,proto3" json:"callables,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetVarDecl() []*VarDeclaration {
	if x != nil {
		return x.VarDecl
	}
	return nil
}

func (x *Block) GetStmts() []*Statement {
	if x != nil {
		return x.Stmts
	}
	return nil
}

func (x *Block) GetCallables() []*Callable {
	if x != nil {
		return x.Callables
	}
	return nil
}

type Callable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind Callable_CallKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.Callable_CallKind" json:"kind,omitempty"`
	// Types that are assignable to Call:
	//
	//	*Callable_FuncDecl
	//	*Callable_ProcDecl
	Call isCallable_Call `protobuf_oneof:"call"`
}

func (x *Callable) Reset() {
	*x = Callable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Callable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Callable) ProtoMessage() {}

func (x *Callable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Callable.ProtoReflect.Descriptor instead.
func (*Callable) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{2}
}

func (x *Callable) GetKind() Callable_CallKind {
	if x != nil {
		return x.Kind
	}
	return Callable_Func
}

func (m *Callable) GetCall() isCallable_Call {
	if m != nil {
		return m.Call
	}
	return nil
}

func (x *Callable) GetFuncDecl() *FuncDeclaration {
	if x, ok := x.GetCall().(*Callable_FuncDecl); ok {
		return x.FuncDecl
	}
	return nil
}

func (x *Callable) GetProcDecl() *ProcDeclaration {
	if x, ok := x.GetCall().(*Callable_ProcDecl); ok {
		return x.ProcDecl
	}
	return nil
}

type isCallable_Call interface {
	isCallable_Call()
}

type Callable_FuncDecl struct {
	FuncDecl *FuncDeclaration `protobuf:"bytes,2,opt,name=funcDecl,proto3,oneof"`
}

type Callable_ProcDecl struct {
	ProcDecl *ProcDeclaration `protobuf:"bytes,3,opt,name=procDecl,proto3,oneof"`
}

func (*Callable_FuncDecl) isCallable_Call() {}

func (*Callable_ProcDecl) isCallable_Call() {}

type FormalParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind FormalParameter_FPKind `protobuf:"varint,1,opt,name=kind,proto3,enum=Pasc.FormalParameter_FPKind" json:"kind,omitempty"`
	// Types that are assignable to Fp:
	//
	//	*FormalParameter_FHead
	//	*FormalParameter_PHead
	//	*FormalParameter_VParam
	//	*FormalParameter_ValParam
	Fp isFormalParameter_Fp `protobuf_oneof:"fp"`
}

func (x *FormalParameter) Reset() {
	*x = FormalParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormalParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormalParameter) ProtoMessage() {}

func (x *FormalParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormalParameter.ProtoReflect.Descriptor instead.
func (*FormalParameter) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{3}
}

func (x *FormalParameter) GetKind() FormalParameter_FPKind {
	if x != nil {
		return x.Kind
	}
	return FormalParameter_FuncHead
}

func (m *FormalParameter) GetFp() isFormalParameter_Fp {
	if m != nil {
		return m.Fp
	}
	return nil
}

func (x *FormalParameter) GetFHead() *FuncHeading {
	if x, ok := x.GetFp().(*FormalParameter_FHead); ok {
		return x.FHead
	}
	return nil
}

func (x *FormalParameter) GetPHead() *ProcHeading {
	if x, ok := x.GetFp().(*FormalParameter_PHead); ok {
		return x.PHead
	}
	return nil
}

func (x *FormalParameter) GetVParam() *VariableParam {
	if x, ok := x.GetFp().(*FormalParameter_VParam); ok {
		return x.VParam
	}
	return nil
}

func (x *FormalParameter) GetValParam() *ValueParam {
	if x, ok := x.GetFp().(*FormalParameter_ValParam); ok {
		return x.ValParam
	}
	return nil
}

type isFormalParameter_Fp interface {
	isFormalParameter_Fp()
}

type FormalParameter_FHead struct {
	FHead *FuncHeading `protobuf:"bytes,2,opt,name=fHead,proto3,oneof"`
}

type FormalParameter_PHead struct {
	PHead *ProcHeading `protobuf:"bytes,3,opt,name=pHead,proto3,oneof"`
}

type FormalParameter_VParam struct {
	VParam *VariableParam `protobuf:"bytes,4,opt,name=vParam,proto3,oneof"`
}

type FormalParameter_ValParam struct {
	ValParam *ValueParam `protobuf:"bytes,5,opt,name=valParam,proto3,oneof"`
}

func (*FormalParameter_FHead) isFormalParameter_Fp() {}

func (*FormalParameter_PHead) isFormalParameter_Fp() {}

func (*FormalParameter_VParam) isFormalParameter_Fp() {}

func (*FormalParameter_ValParam) isFormalParameter_Fp() {}

type VariableParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Type  *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *VariableParam) Reset() {
	*x = VariableParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableParam) ProtoMessage() {}

func (x *VariableParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableParam.ProtoReflect.Descriptor instead.
func (*VariableParam) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{4}
}

func (x *VariableParam) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *VariableParam) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type ValueParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Type  *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ValueParam) Reset() {
	*x = ValueParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueParam) ProtoMessage() {}

func (x *ValueParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueParam.ProtoReflect.Descriptor instead.
func (*ValueParam) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{5}
}

func (x *ValueParam) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ValueParam) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type FuncHeading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params     []*FormalParameter `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	ReturnType *Type              `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
}

func (x *FuncHeading) Reset() {
	*x = FuncHeading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncHeading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncHeading) ProtoMessage() {}

func (x *FuncHeading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncHeading.ProtoReflect.Descriptor instead.
func (*FuncHeading) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{6}
}

func (x *FuncHeading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FuncHeading) GetParams() []*FormalParameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *FuncHeading) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

type ProcHeading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params     []*FormalParameter `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	ReturnType *Type              `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
}

func (x *ProcHeading) Reset() {
	*x = ProcHeading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcHeading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcHeading) ProtoMessage() {}

func (x *ProcHeading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcHeading.ProtoReflect.Descriptor instead.
func (*ProcHeading) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{7}
}

func (x *ProcHeading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcHeading) GetParams() []*FormalParameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProcHeading) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

// ////////////////////////////////
//
//	DECLARATIONS
//
// ////////////////////////////////
type FuncDeclaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncHeading *FuncHeading `protobuf:"bytes,1,opt,name=funcHeading,proto3" json:"funcHeading,omitempty"`
	Blk         *Block       `protobuf:"bytes,2,opt,name=blk,proto3" json:"blk,omitempty"`
	Dir         string       `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *FuncDeclaration) Reset() {
	*x = FuncDeclaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncDeclaration) ProtoMessage() {}

func (x *FuncDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncDeclaration.ProtoReflect.Descriptor instead.
func (*FuncDeclaration) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{8}
}

func (x *FuncDeclaration) GetFuncHeading() *FuncHeading {
	if x != nil {
		return x.FuncHeading
	}
	return nil
}

func (x *FuncDeclaration) GetBlk() *Block {
	if x != nil {
		return x.Blk
	}
	return nil
}

func (x *FuncDeclaration) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ProcDeclaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcHead *ProcHeading `protobuf:"bytes,1,opt,name=procHead,proto3" json:"procHead,omitempty"`
	Blk      *Block       `protobuf:"bytes,2,opt,name=blk,proto3" json:"blk,omitempty"`
	Dir      string       `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *ProcDeclaration) Reset() {
	*x = ProcDeclaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcDeclaration) ProtoMessage() {}

func (x *ProcDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcDeclaration.ProtoReflect.Descriptor instead.
func (*ProcDeclaration) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{9}
}

func (x *ProcDeclaration) GetProcHead() *ProcHeading {
	if x != nil {
		return x.ProcHead
	}
	return nil
}

func (x *ProcDeclaration) GetBlk() *Block {
	if x != nil {
		return x.Blk
	}
	return nil
}

func (x *ProcDeclaration) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type VarDeclaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Expression `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type *Type       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *VarDeclaration) Reset() {
	*x = VarDeclaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_program_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarDeclaration) ProtoMessage() {}

func (x *VarDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_program_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarDeclaration.ProtoReflect.Descriptor instead.
func (*VarDeclaration) Descriptor() ([]byte, []int) {
	return file_proto_program_proto_rawDescGZIP(), []int{10}
}

func (x *VarDeclaration) GetName() *Expression {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *VarDeclaration) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_proto_program_proto protoreflect.FileDescriptor

var file_proto_program_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x50, 0x61, 0x73, 0x63, 0x1a, 0x10, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x73,
	0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x8c,
	0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2e, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x44,
	0x65, 0x63, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x56, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x76, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x6d, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x73, 0x74, 0x6d, 0x74, 0x73, 0x12,
	0x2c, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0xc9, 0x01,
	0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x44,
	0x65, 0x63, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x12, 0x33, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x44, 0x65, 0x63,
	0x6c, 0x22, 0x1e, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x75, 0x6e, 0x63, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x63, 0x10,
	0x01, 0x42, 0x06, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x22, 0xc2, 0x02, 0x0a, 0x0f, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x30, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x50, 0x61,
	0x73, 0x63, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x2e, 0x46, 0x50, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x29, 0x0a, 0x05, 0x66, 0x48, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x48, 0x00, 0x52, 0x05, 0x66, 0x48, 0x65, 0x61, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x48,
	0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x50, 0x61, 0x73, 0x63,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x05,
	0x70, 0x48, 0x65, 0x61, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x76, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x06, 0x76, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x2e, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x22, 0x42, 0x0a, 0x06, 0x46, 0x50, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0c,
	0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x48, 0x65, 0x61, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x63, 0x48, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x61,
	0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x10, 0x03, 0x42, 0x04, 0x0a, 0x02, 0x66, 0x70, 0x22, 0x45,
	0x0a, 0x0d, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x42, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x7c, 0x0a, 0x0b, 0x46, 0x75, 0x6e,
	0x63, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50,
	0x61, 0x73, 0x63, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2a, 0x0a, 0x0a, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7c, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x48,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x61, 0x73,
	0x63, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2a, 0x0a, 0x0a, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x77, 0x0a, 0x0f, 0x46, 0x75, 0x6e, 0x63, 0x44, 0x65, 0x63,
	0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x63,
	0x48, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x0b, 0x66, 0x75, 0x6e, 0x63, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a,
	0x03, 0x62, 0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x73,
	0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x03, 0x62, 0x6c, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x71,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x48,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x1d, 0x0a, 0x03, 0x62, 0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x03, 0x62, 0x6c, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69,
	0x72, 0x22, 0x56, 0x0a, 0x0e, 0x56, 0x61, 0x72, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x6b, 0x67,
	0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_program_proto_rawDescOnce sync.Once
	file_proto_program_proto_rawDescData = file_proto_program_proto_rawDesc
)

func file_proto_program_proto_rawDescGZIP() []byte {
	file_proto_program_proto_rawDescOnce.Do(func() {
		file_proto_program_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_program_proto_rawDescData)
	})
	return file_proto_program_proto_rawDescData
}

var file_proto_program_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_program_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_program_proto_goTypes = []interface{}{
	(Callable_CallKind)(0),      // 0: Pasc.Callable.CallKind
	(FormalParameter_FPKind)(0), // 1: Pasc.FormalParameter.FPKind
	(*Program)(nil),             // 2: Pasc.Program
	(*Block)(nil),               // 3: Pasc.Block
	(*Callable)(nil),            // 4: Pasc.Callable
	(*FormalParameter)(nil),     // 5: Pasc.FormalParameter
	(*VariableParam)(nil),       // 6: Pasc.VariableParam
	(*ValueParam)(nil),          // 7: Pasc.ValueParam
	(*FuncHeading)(nil),         // 8: Pasc.FuncHeading
	(*ProcHeading)(nil),         // 9: Pasc.ProcHeading
	(*FuncDeclaration)(nil),     // 10: Pasc.FuncDeclaration
	(*ProcDeclaration)(nil),     // 11: Pasc.ProcDeclaration
	(*VarDeclaration)(nil),      // 12: Pasc.VarDeclaration
	(TokenKind)(0),              // 13: Pasc.TokenKind
	(*Statement)(nil),           // 14: Pasc.Statement
	(*Type)(nil),                // 15: Pasc.Type
	(*Expression)(nil),          // 16: Pasc.Expression
}
var file_proto_program_proto_depIdxs = []int32{
	13, // 0: Pasc.Program.kind:type_name -> Pasc.TokenKind
	3,  // 1: Pasc.Program.block:type_name -> Pasc.Block
	12, // 2: Pasc.Block.varDecl:type_name -> Pasc.VarDeclaration
	14, // 3: Pasc.Block.stmts:type_name -> Pasc.Statement
	4,  // 4: Pasc.Block.callables:type_name -> Pasc.Callable
	0,  // 5: Pasc.Callable.kind:type_name -> Pasc.Callable.CallKind
	10, // 6: Pasc.Callable.funcDecl:type_name -> Pasc.FuncDeclaration
	11, // 7: Pasc.Callable.procDecl:type_name -> Pasc.ProcDeclaration
	1,  // 8: Pasc.FormalParameter.kind:type_name -> Pasc.FormalParameter.FPKind
	8,  // 9: Pasc.FormalParameter.fHead:type_name -> Pasc.FuncHeading
	9,  // 10: Pasc.FormalParameter.pHead:type_name -> Pasc.ProcHeading
	6,  // 11: Pasc.FormalParameter.vParam:type_name -> Pasc.VariableParam
	7,  // 12: Pasc.FormalParameter.valParam:type_name -> Pasc.ValueParam
	15, // 13: Pasc.VariableParam.type:type_name -> Pasc.Type
	15, // 14: Pasc.ValueParam.type:type_name -> Pasc.Type
	5,  // 15: Pasc.FuncHeading.params:type_name -> Pasc.FormalParameter
	15, // 16: Pasc.FuncHeading.returnType:type_name -> Pasc.Type
	5,  // 17: Pasc.ProcHeading.params:type_name -> Pasc.FormalParameter
	15, // 18: Pasc.ProcHeading.returnType:type_name -> Pasc.Type
	8,  // 19: Pasc.FuncDeclaration.funcHeading:type_name -> Pasc.FuncHeading
	3,  // 20: Pasc.FuncDeclaration.blk:type_name -> Pasc.Block
	9,  // 21: Pasc.ProcDeclaration.procHead:type_name -> Pasc.ProcHeading
	3,  // 22: Pasc.ProcDeclaration.blk:type_name -> Pasc.Block
	16, // 23: Pasc.VarDeclaration.name:type_name -> Pasc.Expression
	15, // 24: Pasc.VarDeclaration.type:type_name -> Pasc.Type
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_program_proto_init() }
func file_proto_program_proto_init() {
	if File_proto_program_proto != nil {
		return
	}
	file_proto_type_proto_init()
	file_proto_token_proto_init()
	file_proto_expression_proto_init()
	file_proto_statement_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_program_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Callable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormalParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncHeading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcHeading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncDeclaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcDeclaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_program_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarDeclaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_program_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Callable_FuncDecl)(nil),
		(*Callable_ProcDecl)(nil),
	}
	file_proto_program_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*FormalParameter_FHead)(nil),
		(*FormalParameter_PHead)(nil),
		(*FormalParameter_VParam)(nil),
		(*FormalParameter_ValParam)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_program_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_program_proto_goTypes,
		DependencyIndexes: file_proto_program_proto_depIdxs,
		EnumInfos:         file_proto_program_proto_enumTypes,
		MessageInfos:      file_proto_program_proto_msgTypes,
	}.Build()
	File_proto_program_proto = out.File
	file_proto_program_proto_rawDesc = nil
	file_proto_program_proto_goTypes = nil
	file_proto_program_proto_depIdxs = nil
}
