// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/type.proto

package serializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type_TypeKind int32

const (
	Type_INTEGER Type_TypeKind = 0
	Type_REAL    Type_TypeKind = 1
	Type_BOOLEAN Type_TypeKind = 2
	Type_CHAR    Type_TypeKind = 3
	Type_VOID    Type_TypeKind = 4
)

// Enum value maps for Type_TypeKind.
var (
	Type_TypeKind_name = map[int32]string{
		0: "INTEGER",
		1: "REAL",
		2: "BOOLEAN",
		3: "CHAR",
		4: "VOID",
	}
	Type_TypeKind_value = map[string]int32{
		"INTEGER": 0,
		"REAL":    1,
		"BOOLEAN": 2,
		"CHAR":    3,
		"VOID":    4,
	}
)

func (x Type_TypeKind) Enum() *Type_TypeKind {
	p := new(Type_TypeKind)
	*p = x
	return p
}

func (x Type_TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_type_proto_enumTypes[0].Descriptor()
}

func (Type_TypeKind) Type() protoreflect.EnumType {
	return &file_proto_type_proto_enumTypes[0]
}

func (x Type_TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_TypeKind.Descriptor instead.
func (Type_TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 0}
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tk Type_TypeKind `protobuf:"varint,1,opt,name=tk,proto3,enum=Pasc.Type_TypeKind" json:"tk,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Type_Int
	//	*Type_Real_
	//	*Type_Bool
	//	*Type_Char_
	//	*Type_Void_
	Type isType_Type `protobuf_oneof:"type"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetTk() Type_TypeKind {
	if x != nil {
		return x.Tk
	}
	return Type_INTEGER
}

func (m *Type) GetType() isType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Type) GetInt() *Type_Integer {
	if x, ok := x.GetType().(*Type_Int); ok {
		return x.Int
	}
	return nil
}

func (x *Type) GetReal() *Type_Real {
	if x, ok := x.GetType().(*Type_Real_); ok {
		return x.Real
	}
	return nil
}

func (x *Type) GetBool() *Type_Boolean {
	if x, ok := x.GetType().(*Type_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *Type) GetChar() *Type_Char {
	if x, ok := x.GetType().(*Type_Char_); ok {
		return x.Char
	}
	return nil
}

func (x *Type) GetVoid() *Type_Void {
	if x, ok := x.GetType().(*Type_Void_); ok {
		return x.Void
	}
	return nil
}

type isType_Type interface {
	isType_Type()
}

type Type_Int struct {
	Int *Type_Integer `protobuf:"bytes,2,opt,name=int,proto3,oneof"`
}

type Type_Real_ struct {
	Real *Type_Real `protobuf:"bytes,3,opt,name=real,proto3,oneof"`
}

type Type_Bool struct {
	Bool *Type_Boolean `protobuf:"bytes,4,opt,name=bool,proto3,oneof"`
}

type Type_Char_ struct {
	Char *Type_Char `protobuf:"bytes,5,opt,name=char,proto3,oneof"`
}

type Type_Void_ struct {
	Void *Type_Void `protobuf:"bytes,6,opt,name=void,proto3,oneof"`
}

func (*Type_Int) isType_Type() {}

func (*Type_Real_) isType_Type() {}

func (*Type_Bool) isType_Type() {}

func (*Type_Char_) isType_Type() {}

func (*Type_Void_) isType_Type() {}

type Type_Integer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Type_Integer) Reset() {
	*x = Type_Integer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Integer) ProtoMessage() {}

func (x *Type_Integer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Integer.ProtoReflect.Descriptor instead.
func (*Type_Integer) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Type_Integer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Type_Boolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Type_Boolean) Reset() {
	*x = Type_Boolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Boolean) ProtoMessage() {}

func (x *Type_Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Boolean.ProtoReflect.Descriptor instead.
func (*Type_Boolean) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Type_Boolean) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Type_Real struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Type_Real) Reset() {
	*x = Type_Real{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Real) ProtoMessage() {}

func (x *Type_Real) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Real.ProtoReflect.Descriptor instead.
func (*Type_Real) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Type_Real) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Type_Char struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Type_Char) Reset() {
	*x = Type_Char{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Char) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Char) ProtoMessage() {}

func (x *Type_Char) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Char.ProtoReflect.Descriptor instead.
func (*Type_Char) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Type_Char) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Type_Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Type_Void) Reset() {
	*x = Type_Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Void) ProtoMessage() {}

func (x *Type_Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Void.ProtoReflect.Descriptor instead.
func (*Type_Void) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Type_Void) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_type_proto protoreflect.FileDescriptor

var file_proto_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x50, 0x61, 0x73, 0x63, 0x22, 0xd0, 0x03, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x23, 0x0a, 0x02, 0x74, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x02, 0x74, 0x6b, 0x12, 0x26, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50,
	0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x48, 0x00, 0x52,
	0x04, 0x72, 0x65, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12,
	0x25, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x48, 0x00,
	0x52, 0x04, 0x63, 0x68, 0x61, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x76, 0x6f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x48, 0x00, 0x52, 0x04, 0x76, 0x6f, 0x69, 0x64, 0x1a, 0x1d, 0x0a,
	0x07, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x1d, 0x0a, 0x07,
	0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x52,
	0x65, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x42, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x52, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x4f, 0x49,
	0x44, 0x10, 0x04, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_type_proto_rawDescOnce sync.Once
	file_proto_type_proto_rawDescData = file_proto_type_proto_rawDesc
)

func file_proto_type_proto_rawDescGZIP() []byte {
	file_proto_type_proto_rawDescOnce.Do(func() {
		file_proto_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_type_proto_rawDescData)
	})
	return file_proto_type_proto_rawDescData
}

var file_proto_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_type_proto_goTypes = []interface{}{
	(Type_TypeKind)(0),   // 0: Pasc.Type.TypeKind
	(*Type)(nil),         // 1: Pasc.Type
	(*Type_Integer)(nil), // 2: Pasc.Type.Integer
	(*Type_Boolean)(nil), // 3: Pasc.Type.Boolean
	(*Type_Real)(nil),    // 4: Pasc.Type.Real
	(*Type_Char)(nil),    // 5: Pasc.Type.Char
	(*Type_Void)(nil),    // 6: Pasc.Type.Void
}
var file_proto_type_proto_depIdxs = []int32{
	0, // 0: Pasc.Type.tk:type_name -> Pasc.Type.TypeKind
	2, // 1: Pasc.Type.int:type_name -> Pasc.Type.Integer
	4, // 2: Pasc.Type.real:type_name -> Pasc.Type.Real
	3, // 3: Pasc.Type.bool:type_name -> Pasc.Type.Boolean
	5, // 4: Pasc.Type.char:type_name -> Pasc.Type.Char
	6, // 5: Pasc.Type.void:type_name -> Pasc.Type.Void
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_type_proto_init() }
func file_proto_type_proto_init() {
	if File_proto_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Integer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Boolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Real); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Char); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_type_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Type_Int)(nil),
		(*Type_Real_)(nil),
		(*Type_Bool)(nil),
		(*Type_Char_)(nil),
		(*Type_Void_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_type_proto_goTypes,
		DependencyIndexes: file_proto_type_proto_depIdxs,
		EnumInfos:         file_proto_type_proto_enumTypes,
		MessageInfos:      file_proto_type_proto_msgTypes,
	}.Build()
	File_proto_type_proto = out.File
	file_proto_type_proto_rawDesc = nil
	file_proto_type_proto_goTypes = nil
	file_proto_type_proto_depIdxs = nil
}
